# Generated by Django 3.0.8 on 2020-07-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200715_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publicado',)},
        ),
    ]
